version: '3.7'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: fake_password
      POSTGRES_DB: school
    volumes:
      - postgres-data:/var/lib/postgresql/data

  application_service:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres-data: